### ISSUE TITLE
Android not dismissing Chrome custom tab with WebBrowser.dismissBrowser()

### ISSUE THREAD

**Issue by GollyJer** [expo/auth0-example#2]
Hi guys.  I'm not having any luck getting this to work properly with Android 7.1.1.
If you want to see it, I have a video taken from my phone, not an emulator.  It's weird, you can kind of see it dismiss something but then the browser remains in the foreground. Let me know what else I can provide to to help troubleshoot.

You can hit me up in the Exponent Slack via DM if you want the video.  Can't post here. :/

**Comment by janicduplessis** [comment]
Looking at this issue today

**Comment by janicduplessis** [comment]
The issue was fixed in Exponent, it will work properly in the next release of the Android app.
