### ISSUE TITLE
No id_token returning in response

### ISSUE THREAD

**Issue by justinkchen** [expo/auth0-example#24]
There is no id_token in the response when using this example. How do we fix this?

**Comment by aymericbouzy** [comment]
I've managed to get one using https://github.com/expo/auth0-example/issues/16

**Comment by on-delete** [comment]
Hey @justinkchen, the problem within this example is, that you have to set the response_type: 'id_token' and additionally nonce: 'example', to get the jwt within the response. This config is working for me:

`authUrl: '${auth0Domain}/authorize' + toQueryString({
 client_id: auth0ClientId,
            response_type: 'id_token',
            scope: 'openid name',
            redirect_uri: redirectUrl,
            nonce: 'example',
          }),`

I also thought about doing a PR to fix this, but don't know if this repo is still actively maintained.
