### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by aymericbouzy** [expo/auth0-example#25]
Hi,

Thanks for this example. I'm struggling with logout: I've tried this, but without success:

```js
await WebBrowser.openBrowserAsync(
  "https://goferworkondemand.eu.auth0.com/v2/logout",
)
```

How should I logout my user? Thanks for your help.

**Comment by venepe** [comment]
After registering the logout url with auth0, this worked for me:

``const returnUrl = `com.my.app://d0able.auth0.com/${Platform.OS}/com.my.app/callback`;``
``await WebBrowser.openBrowserAsync(`https://mytenant.auth0.com/v2/logout?client_id=${auth0ClientId}&returnTo=${returnUrl}`)``

**Comment by venepe** [comment]
After registering the logout url with auth0, this worked for me:

`` const returnUrl = `com.my.app://mytenant.auth0.com/${Platform.OS}/com.my.app/callback`; ``
`` await WebBrowser.openBrowserAsync(`https://mytenant.auth0.com/v2/logout?client_id=${auth0ClientId}&returnTo=${returnUrl}`) ``

**Comment by aymericbouzy** [comment]
After discussing it with the Auth0 team, there are a few ways to "logout" a user:
1. If the user is only using the session from the application (there is no web platform where the user authenticates for instance), you can pass `prompt=login`, and that way, the user will be able to connect with a different account even when the user is not really logged out. 
2. If you set an expiration time for the SSO cookie of 1 minute, it's almost as if the user is disconnected right away. There is no way to set it to less than 1 minute.
3. Opening a browser window with the `/v2/logout` url does invalidate the session, and you should indeed provide the `client_id` and `returnTo` parameters (be careful to URL encode the returnTo URL). However, be careful where the cookie was set : on iOS, the cookies are handled in a special fashion, and it was set in an unexpected location when using the passwordless link method.
