### ISSUE TITLE
Is it possible to use localhost in the redirect for dev environment?

### ISSUE THREAD

**Issue by lucastobrazil** [expo/auth0-example#5]
LOVE this tutorial, it was super easy to follow and worked perfectly as a template for my own app's login page :)

Question though... why do we have to use the `exp://...direct` address for the redirect? Could (in dev mode) we set it to localhost? 

My flow is: 
`Click Login -> Popup WebView with my server's login -> Hit callback url via Linking eventListener`

**Comment by charlesvinette** [comment]
Hello Lucas! Thanks for the kind words. Sorry it took me a little while to get back to you. The team released a new AuthSession module in SDK 21 to facilitate this particular flow, or any other web browser/auth flow for that matter. I just updated the example, you should take a look and maybe make the change in your application, it is way cleaner this way and also easier to work in a team environment :)

**Comment by lucastobrazil** [comment]
Awesome, thanks @charlesvinette !

**Comment by charlesvinette** [comment]
Not a problem!!
