### ISSUE TITLE
Any work around for id_token?

### ISSUE THREAD

**Issue by ice-chillios** [expo/auth0-example#6]
For now, Auth0 removed support for Legacy: Delegation ID Token. You have to manually contact with them to enable this option. Is there any other solution to connect expo app with Auth0? 

![image](https://user-images.githubusercontent.com/17621507/29872103-72d2ffd8-8d8e-11e7-8b49-d8a9065e91f5.png)

**Comment by ice-chillios** [comment]
Seems to be obsolete for now when PRs were merged. @charlesvinette should we keep this issue open for now when there are still PRs/issues related to this on other repositories?

**Comment by charlesvinette** [comment]
Hey @dsznajder! Thanks for helping out with the example.Let's leave it open for now since it is referenced elsewhere, however it shouldn't be an issue anymore if we follow the new docs on Auth0.

**Comment by nandito** [comment]
I've spent some time today on checking how Expo and Auth0 work together. For me this example app works fine, I just had to use the `access_token` in an extra fetch request to get the user info. 

_(Probably there are better ways to this, but I allocated 1 hour for this research.)_

Here's my modified `handleParams` function.

```js
handleParams = (responseObj) => {
  if (responseObj.error) {
    Alert.alert('Error', responseObj.error_description
      || 'something went wrong while logging in');
    return;
  }

  fetch(`${auth0Domain}/userinfo?access_token=${responseObj.access_token}`)
    .then(response => {
      if (response.status === 200) {
        response.json().then(parsedResponse => {
          const { nickname, email, picture } = parsedResponse

          this.setState({ nickname, email, picture });
        })
      }
      else {
        console.log('Something went wrong. ErrorCode: ', response.status);
      }
    })
}
```

To get the user's nickname, email and picture and not just the sub, I also had to turn of the `OIDC Conformant` switch. (Auth0 dashboard: Clients page - Settings tab - Advanced settings - OAuth tab.)

**Comment by mitel** [comment]
Actually the issue is with setting the right scope when when configuring the AuthSession:

```JavaScript
const result = await AuthSession.startAsync({
  authUrl:
    `${config.auth0Domain}/authorize` +
        toQueryString({
	  client_id: config.clientId,
	  response_type: "token",
          scope: "openid profile", // make sure OIDC compliance flag is off as stated in the above comment
	  redirect_uri: redirectUrl
        })
});
```

This way you don't need the second fetch.

**Comment by aymericbouzy** [comment]
I have managed to obtain an id_token by implementing https://auth0.com/docs/flows/guides/mobile-login-flow/add-login-using-mobile-login-flow

However, the doc suggests using the `crypto` Node.js module, which is not available in Expo. Apparently, crypto API is on the way : https://expo.canny.io/feature-requests/p/crypto-api

For the time being, I'm using HTTP to get the crypto random number.
