### ISSUE TITLE
_handleAuth0Redirect returns an error

### ISSUE THREAD

**Issue by dhwrwmgwra** [expo/auth0-example#7]

**Comment by anp** [comment]
Please include more information here and we can reopen. Thanks!

**Comment by dhwrwmgwra** [comment]
![screen shot 2017-09-12 at 12 36 43 pm](https://user-images.githubusercontent.com/17001301/30312419-14b0df1e-97b7-11e7-8c24-2af1120eb2a6.png)

@dikaiosune I get this error
